# Generated by Django 3.2.6 on 2024-07-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semfour',
            name='select_sub',
            field=models.CharField(choices=[('ESS', 'ESS'), ('ALGORITHMS', 'ALGORITHMS'), ('DBMS', 'DBMS'), ('OS', 'OS'), ('OOPS', 'OOPS'), ('AIML', 'AIML')], max_length=100),
        ),
        migrations.AlterField(
            model_name='semone',
            name='select_sub',
            field=models.CharField(choices=[('M1', 'M1'), ('CHEMISTRY', 'CHEMISTRY'), ('PHYSICS', 'PHYSICS'), ('PYTHON', 'PYTHON'), ('ENGLISH', 'ENGLISH')], max_length=100),
        ),
        migrations.AlterField(
            model_name='semthree',
            name='select_sub',
            field=models.CharField(choices=[('M3', 'M3'), ('DSA', 'DSA'), ('OOPS', 'OOPS'), ('FDS', 'FDS'), ('DPCO', 'DPCO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='semtwo',
            name='select_sub',
            field=models.CharField(choices=[('M2', 'M2'), ('PHYSICS', 'PHYSICS'), ('BEEE', 'BEEE'), ('C', 'C'), ('ENGINEERING GRAPHICS', 'ENGINEERING GRAPHICS'), ('ENGLISH2', 'ENGLISH2')], max_length=100),
        ),
    ]
